production:
    adapter: postgresql
    encoding: utf8
    host: db
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    pool: <%= ENV['DB_POOL'] %>
test:
  adapter: postgresql
  encoding: utf8
  host: db
  database: <%= ENV['POSTGRES_TEST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
